### ISSUE TITLE
Atom en français

### ISSUE THREAD

**Issue by Spirou4D** [Spidersouris/atom-french-menu#1]
Salut,
Je voudrais savoir comment on installe ce travail pour avoir Atom en français, svp? Je n'ai aucune explication.

**Comment by spidersouris** [comment]
Salut !

Il est vrai que j'aurais du préciser la méthode d'installation. J'ai complètement oublié de le faire, désolé.

Pour installer ce package, il te suffit d'ouvrir Atom, de te rendre dans les paramètres (Settings), de cliquer sur l'onglet « Installer » (Install) et de rechercher « french-menu ». Ensuite, clique sur « Install », et, une fois l'installation terminée, redémarre Atom.

Je vais ajouter les instructions pour installer le package dans les heures à venir. Merci de me l'avoir fait remarquer 👍

**Comment by Spirou4D** [comment]
Ok Sympa ta réponse et ton travail sur Atom que je découvre: très bel
interface sobre et esthétique!
Je crois qu'il y a plein de modules complémentaires car je n'ai pas trouvé la
fonction tout déplier tout plier mais ca va venir certainement....
A bientôt peut-être pour échanger.
Spirou4D

EDIT: J'ai trouvé comment "Tout plier et déplier" !
Félicitations et à +

**Comment by spidersouris** [comment]
Merci !
