### ISSUE TITLE
Traductions manquantes et/ou plus disponible

### ISSUE THREAD

**Issue by ghost** [Spidersouris/atom-french-menu#3]
Depuis la mise-à-jour en version 1.17.2, plusieurs traductions n'apparaissent plus dans les menus contextuels ou bien dans l'écran des paramètre.

**Comment by lamboley** [comment]
En utilisant la dernière version disponible sur [atom.io](https://atom.io/packages/french-menu) peux-tu me dire les traductions qu'il te manque et la plateforme sur laquelle tu es ?
