### ISSUE TITLE
Failed to activate the french-menu package

### ISSUE THREAD

**Issue by trallocnivek** [Spidersouris/atom-french-menu#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [french-menu](https://github.com/spidersouris/atom-french-menu) package 0.2.2

### Stack Trace

Failed to activate the french-menu package

```
At unexpected � in file:///C:/Users/nivek/.atom/packages/french-menu/lib/main.coffee:1:1

SyntaxError: unexpected �
  at /packages/french-menu/lib/main.coffee:1:1
```

### Commands

```
```

### Non-Core Packages

```
french-menu 0.2.2 
```

**Comment by lamboley** [comment]
Please, create a new issue if the problem happen again.
